language: c
sudo: required
services:
  - docker
matrix:
  include:
    - os: osx
      env: OCAML_VERSION="4.06"
    - os: linux
      env: DISTRO="alpine" OCAML_VERSION="4.06.0"
    - os: linux
      env: DISTRO="ubuntu-16.04" OCAML_VERSION="4.06.0"
env:
  global:
    - PACKAGE="satysfi"
    - TESTS="false"
before_script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    bash -ex ./travis/linux-before-script.sh ;
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]] ; then
    wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh ;
  else
    echo "Unkown OS name: ${TRAVIS_OS_NAME}" ;
    false ;
  fi
script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    docker run satysfi/satysfi:travis ;
  else
    bash -ex .travis-opam.sh
  fi
