language: c
sudo: required
services:
  - docker
matrix:
  include:
    - os: osx
      env: OCAML_VERSION="4.06"
    - os: linux
      env: DISTRO="alpine" OCAML_VERSION="4.06.0"
    - os: linux
      env: DISTRO="ubuntu-16.04" OCAML_VERSION="4.06.0"
env:
  global:
    - PACKAGE="satysfi"
    - TESTS="false"
before_script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    # for linux (alpine and ubuntu)
    # prepare Dockerfile
    export DOCKERFILE="travis-Dockerfile.tpl" ;
    sed -i "s/%distro%/${DISTRO}/g"               "${DOCKERFILE}" ;
    sed -i "s/%ocaml_version%/${OCAML_VERSION}/g" "${DOCKERFILE}" ;
    sed -i "s/%opambuildtest%/${TESTS}/g"         "${DOCKERFILE}" ;
    sed -i "s/%package%/${PACKAGE}/g"             "${DOCKERFILE}" ;
    cat "${DOCKERFILE}" ;
    docker build --file "${DOCKERFILE}" --tag satysfi/satysfi:travis . ;
  else
    # for osx
    wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
  fi
script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    docker run satysfi/satysfi:travis ;
  else
    bash -ex .travis-opam.sh
  fi
