language: bash
sudo: required
services:
  - docker
matrix:
  include:
    - os: osx
      env: OCAML_VERSION="2.06.0"
    - os: linux
      env: DISTRO="alpine" OCAML_VERSION="2.05.0"
    - os: linux
      env: DISTRO="alpine" OCAML_VERSION="2.06.0"
    - os: linux
      env: DISTRO="ubuntu-16.04" OCAML_VERSION="2.06.0"
env:
  global:
    - PACKAGE="satysfi"
    - OPAMBUILDTEST="true"
    # for osx
    - OPAMYES="true"
    - OPAMJOBS=2
before_script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    # for linux like alpine and ubuntu
    # prepare Dockerfile
    export DOCKERFILE="travis-Dockerfile.tpl" ;
    sed -i "s/%distro%/${DISTRO}/g"               "${DOCKERFILE}" ;
    sed -i "s/%ocaml_version%/${OCAML_VERSION}/g" "${DOCKERFILE}" ;
    sed -i "s/%opambuildtest%/${OPAMBUILDTEST}/g" "${DOCKERFILE}" ;
    sed -i "s/%package%/${PACKAGE}/g"             "${DOCKERFILE}" ;
    cat "${DOCKERFILE}" ;
  else
    # for osx
    # download and install OPAM
    wget -O "${HOME}/opam" https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Darwin ;
    chmod +x "${HOME}/opam" ;
    "${HOME}/opam" init --compiler="${OCAML_VERSION}" ;
    eval `"${HOME}/opam" config env` ;
    
    # install dependency
    "${HOME}/opam" pin add --no-action "${PACKAGE}" ;
    "${HOME}/opam" install --deps-only "${PACKAGE}" ;
  fi
script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    docker build --file "${DOCKERFILE}" --tag satysfi/satysfi:travis . ;
  else
    "${MYOPAM}" install "${PACKAGE}" ;
  fi
