# Documentation: https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis-runner.md

language: c
sudo: required
services:
  - docker
env:
  global:
    - PACKAGE="satysfi"
    - TESTS="false"
matrix:
  include:
    - os: osx
      env: OCAML_VERSION="4.06"
    - os: linux
      env: DISTRO="alpine" OCAML_VERSION="4.05.0"
    - os: linux
      env: DISTRO="alpine" OCAML_VERSION="4.06.0"
    - os: linux
      env: DISTRO="ubuntu-16.04" OCAML_VERSION="4.06.0"
install: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    wget -O .travis-ci.sh https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh ;
  else
    wget -O .travis-ci.sh https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh ;
  fi
script: bash -ex ./.travis-ci.sh
