language: c
sudo: required
services:
  - docker
matrix:
  include:
    - os: osx
      env: OCAML_VERSION="4.06.0"
    - os: linux
      env: DISTRO="alpine" OCAML_VERSION="4.06.0"
    - os: linux
      env: DISTRO="ubuntu-16.04" OCAML_VERSION="4.06.0"
env:
  global:
    - PACKAGE="satysfi"
    - OPAMBUILDTEST="false"
    # For osx
    - OPAMYES="true"
    - OPAMJOBS=2
before_script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    bash -ex ./travis/linux-before-script.sh ;
  elif [[ "${TRAVIS_OS_NAME}" == "osx" ]] ; then
    bash -ex ./travis/osx-before-script.sh ;
  else
    echo "Unkown OS name: ${TRAVIS_OS_NAME}" ;
    false ;
  fi
script: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]] ; then
    docker run satysfi/satysfi:travis ;
  else
    opam install "${PACKAGE}.dev" ;
  fi
